_target_: diffusion_policy.policy.continuous_time_diffusion_policy.ContinuousTimeDiffusionPolicy
_recursive_: False

defaults:
  - inner_model: ??
  - obs_encoder: ??
  - sigma_distribution: rand_log_logistic
  - noise_scheduler: exponential_scheduler
  - scaling: trajectory_kerras_scaling
  - sampler: euler
  - _self_


shape_meta: ${shape_meta}
horizon: ${horizon}
n_action_steps: ${eval:'${n_action_steps}+${n_latency_steps}'}
n_obs_steps: ${n_obs_steps}
num_inference_steps: ${num_inference_steps}
obs_as_local_cond: ${obs_as_local_cond}
obs_as_global_cond: ${obs_as_global_cond}
pred_action_steps_only: ${pred_action_steps_only}
sigma_min: 0.05
sigma_max: 10.0
