_target_: diffusion_policy.policy.diffusion_policy.DiffusionPolicy
_recursive_: False

defaults:
  - inner_model: ??
  - obs_encoder: ??
  - noise_scheduler: DDIM
  - _self_


shape_meta: ${shape_meta}
horizon: ${horizon}
n_action_steps: ${eval:'${n_action_steps}+${n_latency_steps}'}
n_obs_steps: ${n_obs_steps}
num_inference_steps: ${num_inference_steps}
obs_as_local_cond: ${obs_as_local_cond}
obs_as_global_cond: ${obs_as_global_cond}
pred_action_steps_only: ${pred_action_steps_only}
