_target_: diffusion_policy.policy.ot_flow_matching_policy.OTFlowMatchingPolicy
_recursive_: False

defaults:
  - inner_model: ??
  - obs_encoder: ??
  - noise_scheduler: linear_scheduler
  - sigma_distribution@time_distribution: rand_logit_normal
  - sampler: euler
  - _self_


shape_meta: ${shape_meta}
horizon: ${horizon}
n_action_steps: ${eval:'${n_action_steps}+${n_latency_steps}'}
n_obs_steps: ${n_obs_steps}
num_inference_steps: ${num_inference_steps}
obs_as_local_cond: ${obs_as_local_cond}
obs_as_global_cond: ${obs_as_global_cond}
pred_action_steps_only: ${pred_action_steps_only}
target_sigma_min: 0.0

noise_scheduler:
  sigma_min: 0
  sigma_max: 1
  append_zero: False
