dataloader:
  batch_size: 128
  num_workers: 6
  shuffle: True
  pin_memory: True
  persistent_workers: True

val_dataloader:
  batch_size: 128
  num_workers: 6
  shuffle: False
  pin_memory: True
  persistent_workers: True
