dataloader:
  batch_size: 512
  num_workers: 10
  shuffle: True
  pin_memory: True
  persistent_workers: True

val_dataloader:
  batch_size: 512
  num_workers: 10
  shuffle: False
  pin_memory: True
  persistent_workers: True
