defaults:
  - task: doodle
  - ema: ema
  - monitoring
  - data_loader/lowdim@_global_
  - training: training
  - optimizer: adam
  - policy: diffusion_policy
  - override policy/inner_model: unet
  - override policy/obs_encoder: flatten_time
  - _self_

name: doodle
_target_: diffusion_policy.workspace.train_diffusion_workspace.TrainDiffusionWorkspace


policy:
  inner_model:
    down_dims: [256, 512, 1024]

task_name: ${task.name}
shape_meta: ${task.shape_meta}
exp_name: "default"

horizon: 100
n_obs_steps: 1
n_action_steps: 100
n_latency_steps: 0
dataset_obs_steps: ${n_obs_steps}
past_action_visible: False
keypoint_visible_rate: 1.0
obs_as_global_cond: True
obs_as_local_cond: False
pred_action_steps_only: False
num_inference_steps: 100