defaults:
  - task: tool_hang_lowdim_abs
  - ema: power
  - monitoring
  - data_loader/lowdim@_global_
  - training: training
  - optimizer: transformer
  - policy: conditional_flow_matching_policy
  - override policy/inner_model: transformer
  - override policy/obs_encoder: passthrough
  - _self_

name: train_conditional_flow_matching_transformer_lowdim
_target_: diffusion_policy.workspace.train_workspace.TrainWorkspace

shape_meta: ${task.shape_meta}

task_name: ${task.name}
exp_name: "default"

policy:
  target_sigma_min: 0.1

horizon: 16
n_obs_steps: 2
n_action_steps: 8
n_latency_steps: 0
past_action_visible: False
keypoint_visible_rate: 1.0
obs_as_global_cond: True
obs_as_local_cond: False
pred_action_steps_only: False
num_inference_steps: 100

