defaults:
  - task: square_image_abs
  - monitoring
  - data_loader/image@_global_
  # - ema: ema
  - training: training
  - optimizer: transformer
  - policy: ot_flow_matching_policy
  - override policy/inner_model: transformer
  - override policy/obs_encoder: robomimic_obs_encoder
  - _self_

name: train_ot_flow_matching_transformer_hybrid
_target_: diffusion_policy.workspace.train_diffusion_workspace.TrainDiffusionWorkspace

task_name: ${task.name}
shape_meta: ${task.shape_meta}
exp_name: "default"

horizon: 16
n_obs_steps: 2
n_action_steps: 8
n_latency_steps: 0
dataset_obs_steps: ${n_obs_steps}
past_action_visible: False
keypoint_visible_rate: 1.0
obs_as_global_cond: True
obs_as_local_cond: False
pred_action_steps_only: False
num_inference_steps: 100

policy:
  obs_encoder:
    flatten_time: False

ema:
  _target_: diffusion_policy.model.diffusion.ema_model.PowerModel
  stds: [0.050, 0.100]


training:
  checkpoint_every: 10
