defaults:
  - task: square_image_abs
  - monitoring
  - data_loader/image@_global_
  - ema: power
  - training: training
  - optimizer: adam
  - policy: ot_flow_matching_policy
  - override policy/inner_model: unet
  - override policy/obs_encoder: robomimic_obs_encoder
  - _self_

name: train_ot_flow_matching_unet_hybrid
_target_: diffusion_policy.workspace.train_diffusion_workspace.TrainDiffusionWorkspace

task_name: ${task.name}
shape_meta: ${task.shape_meta}
exp_name: "default"

horizon: 16
n_obs_steps: 2
n_action_steps: 8
n_latency_steps: 0
dataset_obs_steps: ${n_obs_steps}
past_action_visible: False
keypoint_visible_rate: 1.0
obs_as_global_cond: True
obs_as_local_cond: False
pred_action_steps_only: False
num_inference_steps: 100

optimizer:
  weight_decay: 1e-3

policy:
  target_sigma_min: 0.01
  inner_model:
    dropout_p: 0.1

checkpoint:
  topk:
    monitor_key: test_mean_score
    mode: max
    k: 5
    format_str: 'epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False

dataloader:
  batch_size: 128

val_dataloader:
  batch_size: 128
