defaults:
  - task: can_lowdim_abs
  - ema: ema
  - monitoring
  - data_loader/lowdim@_global_
  - training: training
  - optimizer: adam
  - policy: diffusion_policy
  - override policy/inner_model: unet
  - override policy/obs_encoder: flatten_time
  - _self_

name: train_diffusion_unet_lowdim
_target_: diffusion_policy.workspace.train_workspace.TrainWorkspace

shape_meta: ${task.shape_meta}

policy:
  inner_model:
    down_dims: [256, 512, 1024]

task_name: ${task.name}
exp_name: "default"

horizon: 16
n_obs_steps: 2
n_action_steps: 8
n_latency_steps: 0
past_action_visible: False
keypoint_visible_rate: 1.0
num_inference_steps: 100

checkpoint:
  topk:
    monitor_key: test_mean_score
    mode: max
    k: 5
    format_str: 'epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False

