defaults:
  - task: blockpush_lowdim_seed
  - ema: ema
  - monitoring
  - data_loader/lowdim@_global_
  - training: training
  - optimizer: transformer
  - policy: diffusion_policy
  - override policy/inner_model: transformer
  - override policy/obs_encoder: passthrough
  - _self_

name: train_diffusion_transformer_lowdim
_target_: diffusion_policy.workspace.train_diffusion_workspace.TrainDiffusionWorkspace

shape_meta:
  action:
    shape: ["${task.action_dim}"]

obs_dim: ${task.obs_dim}
action_dim: ${task.action_dim}
task_name: ${task.name}
exp_name: "default"

horizon: 5
n_obs_steps: 3
n_action_steps: 1
n_latency_steps: 0
past_action_visible: False
keypoint_visible_rate: 1.0
obs_as_global_cond: True
obs_as_local_cond: False
pred_action_steps_only: False
num_inference_steps: 100

checkpoint:
  topk:
    monitor_key: test_mean_score

