defaults:
  - task: real_wam_image
  - ema: ema
  - monitoring
  - data_loader/image@_global_
  - training: training
  - optimizer: adam
  - policy: diffusion_policy
  - override policy/inner_model: unet
  - override policy/obs_encoder: robomimic_obs_encoder
  - _self_

name: train_diffusion_unet_hybrid
_target_: diffusion_policy.workspace.train_workspace.TrainWorkspace

task_name: ${task.name}
shape_meta: ${task.shape_meta}
exp_name: "default"

horizon: 16
n_obs_steps: 2
n_action_steps: 8
n_latency_steps: 0
dataset_obs_steps: ${n_obs_steps}
past_action_visible: False
keypoint_visible_rate: 1.0
obs_as_global_cond: True
obs_as_local_cond: False
pred_action_steps_only: False
num_inference_steps: 8
