defaults:
  - task: lift_image
  - ema: ema
  - monitoring
  - data_loader/image@_global_
  - training: training
  - optimizer: adam
  - policy: diffusion_policy
  - override policy/inner_model: unet
  - override policy/obs_encoder: multi_image_obs_encoder
  - _self_

name: train_diffusion_unet_image
_target_: diffusion_policy.workspace.train_diffusion_workspace.TrainDiffusionWorkspace

task_name: ${task.name}
shape_meta: ${task.shape_meta}
exp_name: "default"

horizon: 16
n_obs_steps: 2
n_action_steps: 8
n_latency_steps: 0
dataset_obs_steps: ${n_obs_steps}
past_action_visible: False
keypoint_visible_rate: 1.0
obs_as_global_cond: True
obs_as_local_cond: False
pred_action_steps_only: False
num_inference_steps: 100

policy:
  obs_encoder:
    rgb_model:
      _target_: diffusion_policy.model.vision.model_getter.get_resnet
      name: resnet18
      weights: IMAGENET1K_V1 # or r3m
    random_crop: False
    use_group_norm: False
    share_rgb_model: True
    imagenet_norm: True

training:
  freeze_encoder: True

checkpoint:
  topk:
    monitor_key: test_mean_score
    mode: max
    k: 5
    format_str: 'epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False

