defaults:
  - robomimic_default
  - _self_

name: lift_image

shape_meta:
  # acceptable types: rgb, low_dim
  obs:
    agentview_image:
      shape: [3, 84, 84]
      type: rgb
    robot0_eye_in_hand_image:
      shape: [3, 84, 84]
      type: rgb
    robot0_eef_pos:
      shape: [3]
      # type default: low_dim
    robot0_eef_quat:
      shape: [4]
    robot0_gripper_qpos:
      shape: [2]
  action: 
    shape: [10]

task_name: lift
dataset_type: ph
dataset_path: data/robomimic/datasets/${task.task_name}/${task.dataset_type}/image_abs.hdf5
abs_action: True
resize_shape: null
crop_shape: [76, 76]

