defaults:
  - robomimic_default
  - _self_

name: lift_lowdim

shape_meta:
  # acceptable types: rgb, low_dim
  obs:
    object:
      shape: [10]
    robot0_eef_pos:
      shape: [3]
      # type default: low_dim
    robot0_eef_quat:
      shape: [4]
    robot0_gripper_qpos:
      shape: [2]
  action: 
    shape: [7]

task_name: lift
dataset_type: ph
dataset_path: data/robomimic/datasets/${task.task_name}/${task.dataset_type}/low_dim.hdf5
abs_action: False

