name: square_image_kp_action

kp_shape: &keypoint_shape [24]

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    agentview_image:
      shape: [3, 84, 84]
      type: rgb
    agentview_keypoints:
      shape: *keypoint_shape
      type: low_dim

  action: 
    shape: *keypoint_shape

task_name: &task_name square
dataset_type: &dataset_type ph
dataset_path: &dataset_path data/robomimic/datasets/${task_name}/${dataset_type}/kp_image.hdf5
abs_action: &abs_action False

env_runner:
  _target_: diffusion_policy.env_runner.robomimic_keypoints_runner.RobomimicKeypointsRunner
  dataset_path: *dataset_path
  shape_meta: *shape_meta
  # costs 1GB per env
  n_train: 6
  n_train_vis: 2
  train_start_idx: 0
  n_test: 50
  n_test_vis: 4
  test_start_seed: 100000
  # use python's eval function as resolver, single-quoted string as argument
  max_steps: ${eval:'500 if "${dataset_type}" == "mh" else 400'}
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  render_obs_key: 'agentview_image'
  fps: 10
  crf: 22
  past_action: ${past_action_visible}
  abs_action: *abs_action
  tqdm_interval_sec: 1.0
  n_envs: 28
  estimate_J: False

# evaluation at this config requires a 16 core 64GB instance.

dataset:
  _target_: diffusion_policy.dataset.robomimic_replay_kp_action_dataset.RobomimicReplayKpActionDataset
  shape_meta: *shape_meta
  dataset_path: *dataset_path
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  abs_action: *abs_action
  use_legacy_normalizer: False
  use_cache: True
  seed: 42
  val_ratio: 0.02
