defaults:
  - robomimic_default
  - _self_

name: tool_hang_image

shape_meta:
  # acceptable types: rgb, low_dim
  obs:
    sideview_image:
      shape: [3, 240, 240]
      type: rgb
    robot0_eye_in_hand_image:
      shape: [3, 240, 240]
      type: rgb
    robot0_eef_pos:
      shape: [3]
      # type default: low_dim
    robot0_eef_quat:
      shape: [4]
    robot0_gripper_qpos:
      shape: [2]
  action: 
    shape: [7]

task_name: tool_hang
dataset_type: ph
dataset_path: data/robomimic/datasets/${task.task_name}/${task.dataset_type}/image.hdf5
abs_action: False

env_runner:
  max_steps: 700

