defaults:
  - robomimic_default
  - _self_

name: transport_image

shape_meta:
  # acceptable types: rgb, low_dim
  obs:
    shouldercamera0_image:
      shape: [3, 84, 84]
      type: rgb
    robot0_eye_in_hand_image:
      shape: [3, 84, 84]
      type: rgb
    robot0_eef_pos:
      shape: [3]
      # type default: low_dim
    robot0_eef_quat:
      shape: [4]
    robot0_gripper_qpos:
      shape: [2]
    shouldercamera1_image:
      shape: [3, 84, 84]
      type: rgb
    robot1_eye_in_hand_image:
      shape: [3, 84, 84]
      type: rgb
    robot1_eef_pos:
      shape: [3]
      # type default: low_dim
    robot1_eef_quat:
      shape: [4]
    robot1_gripper_qpos:
      shape: [2]
  action: 
    shape: [20]

task_name: transport
dataset_type: ph
dataset_path: data/robomimic/datasets/${task.task_name}/${task.dataset_type}/image_abs.hdf5
abs_action: True
resize_shape: null
crop_shape: [76, 76]

env_runner:
  max_steps: 700

