defaults:
  - robomimic_default
  - _self_

name: transport_lowdim

shape_meta:
  # acceptable types: rgb, low_dim
  obs:
    object:
      shape: [41]
    robot0_eef_pos:
      shape: [3]
      # type default: low_dim
    robot0_eef_quat:
      shape: [4]
    robot0_gripper_qpos:
      shape: [2]
    robot1_eef_pos:
      shape: [3]
      # type default: low_dim
    robot1_eef_quat:
      shape: [4]
    robot1_gripper_qpos:
      shape: [2]
  action: 
    shape: [14]

task_name: transport
dataset_type: ph
dataset_path: data/robomimic/datasets/${task.task_name}/${task.dataset_type}/low_dim.hdf5
abs_action: False

env_runner:
  max_steps: 700

